### ISSUE TITLE
Grad Project question

### ISSUE THREAD

**Issue by snehaiyer333** [clauswilke/SDS348_spring2020#16]
When I am trying to set the working directory online in R. I get a message "NA/NaN/Inf in 'y'" after reading in the data. I am not sure what does this mean?

Code that I use:
setwd("//stor//home//myeid//Project")

data <- read_csv("~/Project/data.csv")

**Comment by clauswilke** [comment]
I'm sorry, your question is not answerable like this. First, your code example is not complete, since you must be loading in some libraries. Second, please provide the complete output you see after the `read_csv()` line. Third, what's the contents of `data` after you run your second line? Fourth, what's the contents of "data.csv"? Fifth, why are you setting the working directory if then you use a path starting with `~` (indicating your home directory)? In the code example you provided, the `setwd()` call has absolutely no effect.

**Comment by snehaiyer333** [comment]
Sorry Professor,
This is the code I am using to upload the data.csv (my dataset) to the R environment. I am not sure whether I need the read_csv function or should I directly import it using "import dataset"

Code:
library(ggplot2)
library(tidyverse)
library(dplyr)
library(readr)

## reading file

getwd()
setwd("//stor//home//si4964//Project")
diabetes_data <- read_csv("~/Project/diabetes.csv")
view(diabetes_data)

Output: 
diabetes_data <- read_csv("~/Project/diabetes.csv")
Parsed with column specification:
cols(
  Pregnancies = col_double(),
  Glucose = col_double(),
  BloodPressure = col_double(),
  SkinThickness = col_double(),
  Insulin = col_double(),
  BMI = col_double(),
  DiabetesPedigreeFunction = col_double(),
  Age = col_double(),
  Outcome = col_double()
)
> view(diabetes_data)
>   NA/NaN/Inf in 'y'

**Comment by clauswilke** [comment]
Please run just `diabetes_data` instead of `view(diabetes_data)` and report the output of that. And also, please put your code into backticks, as [described here](https://github.com/clauswilke/SDS348_spring2020/blob/master/README.md), so it's clear what is code and what is not.
