### ISSUE TITLE
Saving as PDF

### ISSUE THREAD

**Issue by 420allday** [clauswilke/SDS348_spring2020#28]
Hi all,

When trying to download a file from jupyter notebook as a pdf I get this error. 
"500 : Internal Server Error
The error was:
nbconvert failed: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex."

I even installed xelatex but still get the same error. I have been saving the files as .html and using online html to pdf converters to get a pdf I can submit to canvas.

How have others been saving as pdf?
What is the proper way to safe as a pdf?

Thanks and happy 4/20

**Comment by rachaelcox** [comment]
Hey! We actually don't recommend the 'save to PDF' as option, since it requires installing an add on for Jupyter. Instead, follow these steps:

1. Kernel -> Restart & Run All
2. File -> Download as -> html (.html)
3. Open the .html in your browser
4. Right click -> Print... -> set Destination to "Save as PDF"

Let me know if you're still having trouble!
