### ISSUE TITLE
Homework 10 Question 2

### ISSUE THREAD

**Issue by 420allday** [clauswilke/SDS348_spring2020#32]
I am getting a very long result when attempting to loop through all features. I am not sure if it is supposed to be this long.

This is the code I am using
```python
from Bio import Entrez, SeqIO

Entrez.email = "your.email@utexas.edu" # put your email here

# download Microcystic aeruginosa genome & save it locally:   #SeqIO.read(handle, "genbank")
with open("Maeruginosa.gb", "w") as outfile:
    handle = Entrez.efetch(db="nucleotide", id="NC_010296", rettype="gbwithparts", retmode="text")
    record = SeqIO.read(handle, "genbank")
    data = handle.read()
    outfile.write(data)
    handle.close()

for feature in record.features:
    print(feature)
```
I did add SeqIO to the import statement and in the download statement because i saw it done that way in the class 20 worksheet. I am getting a result that is probably over 100 pages long, ending with this statement
```python
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)
```
Im assuming it should not be this way. What should I do diferently?
Thanks

**Comment by clauswilke** [comment]
The problem is that you're printing all features, so if there are thousands of features you're generating a very long list. In the end, you're not supposed to print the features, you're only supposed to count. However, printing may be useful as you're developing your solution.

I suggest that while you're developing your code, you use the same `i` / `max_i` trick we used in Class 23:
https://wilkelab.org/classes/SDS348/2020_spring/worksheets/class23_solutions.html

Once your code works as expected, you can then set `max_i` to a very large number to make sure you process all features.
